language: python
python:
 - "2.7"
# command to install dependencies
install: pip install -r requirements.txt
services:
 - postgresql
env:
 - COURSE_MGMT_DATABASE=sqlite:///db.db # postgresql://postgres@localhost/course_mgmt
before_script:
# - psql -c 'create database course_mgmt;' -U postgres
# - python manage.py db init
# - python manage.py db migrate
# - python manage.py db upgrade
# command to run tests
script: sh run_travis_test.sh
after_script:
 - coveralls
 - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: coursemgmt:x30CmBOsCQGoO8jLDLn4rfcs
