language: python
python:
 - "2.7"
# command to install dependencies
install: pip install -r requirements.txt
services:
 - postgresql
before_script:
 - export SQLALCHEMY_DATABASE_URI=postgresql://postgres@localhost/course_mgmt
 - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script: sh run_travis_test.sh
after_script:
 - coveralls
 - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: coursemgmt:x30CmBOsCQGoO8jLDLn4rfcs
