module.exports = {
	ACTIONS: {
		RECEIVE_CLASS: 'RECEIVE_CLASS',
		RECEIVE_CLASSES: 'RECEIVE_CLASSES',
		RECEIVE_COURSES: 'RECEIVE_COURSES',
		RECEIVE_STUDENTS: 'RECEIVE_STUDENTS',
		RENDER_CLASS: 'RENDER_CLASS',
		RENDER_CLASSES: 'RENDER_CLASSES',
		RENDER_FORM: 'RENDER_FORM',
		SETUP: 'SETUP',
		SAVE_FORM: 'SAVE_FORM',
		SHOW_CLASS: 'SHOW_CLASS',
		TOGGLE_LOADING: 'TOGGLE_LOADING',
	}
}
