module.exports = {
	ACTIONS: {
		ADD_COURSE: 'ADD_COURSE',
		RECEIVE_COURSE: 'RECEIVE_COURSE',
		RECEIVE_COURSES: 'RECEIVE_COURSES',
		SHOW_COURSE: 'SHOW_COURSE',
		TOGGLE_FORM: 'TOGGLE_FORM',
		TOGGLE_LOADING: 'TOGGLE_LOADING',
	}
}
