module.exports = {
	ACTIONS: {
		RECEIVE_COURSES: 'RECEIVE_COURSES',
		RECEIVE_LECTURE: 'RECEIVE_LECTURE',
		RECEIVE_LECTURES: 'RECEIVE_LECTURES',
		RENDER_FORM: 'RENDER_FORM',
		RENDER_LECTURE: 'RENDER_LECTURE',
		RENDER_LECTURES: 'RENDER_LECTURES',
		TOGGLE_LOADING: 'TOGGLE_LOADING',
	}
}
