"""empty message

Revision ID: c569865bd269
Revises: None
Create Date: 2016-06-19 18:07:05.485000

"""

# revision identifiers, used by Alembic.
revision = 'c569865bd269'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    ### end Alembic commands ###
