module.exports = {
	ACTIONS: {
		RECEIVE_STUDENT: 'RECEIVE_STUDENT',
		RECEIVE_STUDENTS: 'RECEIVE_STUDENTS',
		RECEIVE_CLASSES: 'RECEIVE_CLASSES',
		RENDER_FORM: 'RENDER_FORM',
		RENDER_STUDENT: 'RENDER_STUDENT',
		RENDER_STUDENTS: 'RENDER_STUDENTS',
		TOGGLE_LOADING: 'TOGGLE_LOADING',
	}
}
